modLoader="javafml"
loaderVersion="[47,)"
license="ARR"

[properties]
"connector:placeholder"=true

[[mods]]
modId="seven_elements"
version="${version}"
displayName="Seven Elements"
authors="_xRickAstley"
description='''
A Minecraft mod that brings a faithful implementation of Genshin Impact's Elemental Combat system in Minecraft
'''

[[dependencies.seven_elements]]
modId="forge"
mandatory=true
versionRange="[47,)"
ordering="NONE"
side="BOTH"

[[dependencies.seven_elements]]
modId="minecraft"
mandatory=true
versionRange="[1.20.1]"
ordering="NONE"
side="BOTH"

[[dependencies.seven_elements]]
modId="connectormod"
mandatory=true
versionRange="*"
ordering="NONE"
side="BOTH"

[[dependencies.seven_elements]]
modId="mixinextras-forge"
mandatory=true
versionRange=">=0.5.0"
ordering="NONE"
side="BOTH"