
import { BiConsumer, BiFunction, Consumer, Function, NonAbstractClass, Predicate, Supplier } from "./FunctionTypes";
import Collector from "./Collector";

import Utils, { RestOrArray } from "./Util";

/**
 * A `Stream` is a sequence of elements that support sequential aggregate operations. This allows
 * for faster and lazy evaluation of elements in an `Iterable<T>` instance, resulting in lesser
 * pointless calculations.
 * 
 * This class implements behavior similar to its Java counterpart: `java.util.stream.Stream`.
 * 
 * ## Stream Operations
 * 
 * A stream has two types of operations: **intermediate** and **terminal**.
 * 
 * ### Intermediate Operations
 * 
 * An **intermediate** operation is an **lazily-applied** operation, where the values are only
 * computed if necessary.
 * 
 * Consider the example below, where `numArray` is an array containing sorted numbers from `1` to 
 * `1,000,000`:
 * ```
 * numArray
 *   .filter(x => x % 11 === 0)
 *   .map(x => x * x)
 *   .slice(0, 5)
 * ```
 * The example below filters around `142,858` elements from our `1,000,000` number array. All 
 * numbers are then squared before only taking the `5` most recent elements.
 * 
 * This results in `285,706` useless calculations, and even when we put the `slice()` operation
 * before the `map()` operation, we still get `142,853` useless calculations from `filter()`.
 * 
 * Now, using the same example but using the `Stream` API instead:
 * ```
 * Stream.of(numArray)
 *   .filter(x => x % 11 === 0)
 *   .map(x => x * x)
 *   .limit(5)
 *   .toArray()
 * ```
 * The example now only performs `50` useless calculations, as the `limit()` operation limits the
 * filtered elements to just `5`, meaning that filtering is stopped after `55` (the 5th multiple of
 * `11`), resulting in only `50` useless calculations from filtering.
 * 
 * This example shows the benefit of using **lazily-applied** `Stream` operations over chaining
 * Array operations unless calculations are intended to be performed on all elements of the Array.
 * 
 * #### Stateful Intermediate Operations
 * 
 * A *stateful* intermediate operation is a `Stream` operation that stores or caches the elements
 * in some manner, such as {@link sorted Stream#sorted()}, which requires **all** elements to be
 * known in order for them to be sorted, and {@link distinct Stream#distinct()}, which stores seen
 * elements in a `Set` in order to guarantee distinctness.
 * 
 * As such, for infinite streams generated by {@link iterate Stream.iterate()}, other intermediate
 * operations such as {@link limit Stream#limit()} should be done first before these operations.
 * 
 * ### Terminal Operations
 * 
 * A **terminal** operation is an operation that consumes the `Stream` and can possibly return a
 * result.
 * 
 * When a **terminal** operation is called, all **intermediate** operations are applied lazily to
 * elements **required** by the **terminal** operation, minimizing useless calculations as much as
 * possible.
 * 
 * For instance, you may use {@link max Stream#max()} to find the maximum element in a `Stream` 
 * according to the specified `comparator`. This operation will consume the stream and return the
 * maximum element.
 * 
 * #### Short-circuiting Terminal operations
 * 
 * A *short-circuting* terminal operation is a `Stream` operation that can terminate ahead of time
 * when calculating further is unnecessary, and is prominent in methods such as 
 * {@link anyMatch Stream#anyMatch()}.
 * 
 * For {@link anyMatch Stream#anyMatch()}, it is only required when **any** element in the stream 
 * passes the given `predicate`. As such, when an element that passes the given `predicate` is 
 * found early, there is no point in calculating further, as the requirement for termination has
 * been already fulfilled.
 * 
 * This method works exactly like its Array variant: {@link Array.some Array#some()}, which 
 * terminates ahead of time when it sees an element that passes the given `predicate` early.
 */
class Stream<T> implements Iterable<T> {
	protected constructor(source: Iterable<T>) {
		this.source = source;
	}

	private readonly source: Iterable<T>;

	public static isIterable(arg: unknown): arg is Iterable<unknown> {
		return Boolean(arg && typeof arg[Symbol.iterator] === "function");
	}

	/**
     * Returns a sequential ordered stream whose elements are based on the specified `Iterable<T>`.
     *
	 * @param iterable The specified iterable of the stream.
     */
	public static of<T>(iterable: Iterable<T>): Stream<T>;
	/**
     * Returns a sequential ordered stream whose elements are the specified values.
     *
	 * @param values The elements of the stream.
     */
	public static of<T>(...values: RestOrArray<T>): Stream<T>;
	public static of<T>(...values: RestOrArray<T> | [Iterable<T>]): Stream<T> {
		return new Stream(
			values.length === 1 && Stream.isIterable(values[0])
				? values[0] as Iterable<T>
				: Utils.normalizeArray(values as RestOrArray<T>)
		);
	}

	/**
	 * Returns an infinite sequential ordered `Stream` whose elements are produced by iterative
	 * application of the `next` function to the initial element `seed`, producing a `Stream`
	 * consisting of elements `seed`, `next(seed)`, `next(next(seed))`, and so on and so forth.
	 * 
	 * The first element of the stream at position `0` will be the provided seed. For elements
	 * after, denoted as position `n`, have their value as the result of iteratively applying the
	 * `next` function to the `seed` and its resulting value `n - 1` times.
	 * 
	 * @param seed The initial element.
	 * @param next The function to be applied to the previous element to produce a new element.
	 */
	public static iterate<T>(seed: T, next: Function<T, T>): Stream<T>
	/**
	 * Returns an infinite sequential ordered `Stream` whose elements are produced by iterative
	 * application of the `next` function to the initial element `seed`, producing a `Stream`
	 * consisting of elements `seed`, `next(seed)`, `next(next(seed))`, and so on and so forth,
	 * with the condition that the element in question, when passed as an argument to the `hasNext`
	 * function, produces a *truthy* value.
	 * 
	 * Note that the resulting stream may be empty if the `hasNext` function produces a *falsy*
	 * value on the `seed` value itself. Otherwise, the first element will be the supplied `seed`
	 * value and the next element (if `hasNext(seed)` is *truthy*) will be the result of applying
	 * the `next` function to the `seed` value, so on and so forth until the `hasNext` function 
	 * returns a *falsy* value.
	 * 
     * @param seed The initial element
     * @param hasNext The predicate to apply to the current element to determine when the stream must terminate.
	 * @param next The function to be applied to the previous element to produce a new element.
	 */
	public static iterate<T>(seed: T, hasNext: Predicate<T>, next: Function<T, T>): Stream<T>
	public static iterate<T>(seed: T, hasNextOrNext: Function<T, T> | Predicate<T>, nextOrNone?: Function<T, T>): Stream<T> {
		const hasNext: Predicate<T> = !nextOrNone
			? () => true
			: hasNextOrNext as Predicate<T>;

		const next: Function<T, T> = !nextOrNone
			? hasNextOrNext as Function<T, T>
			: nextOrNone;

		return new Stream(function* iterate() {
			let value = seed;

			while (hasNext(value)) {
				yield value;

				value = next(value);
			}
		}());
	}

	/**
	 * Returns an empty sequential `Stream`.
	 */
	public static empty<T>(): Stream<T> {
		return new Stream(function* empty() {}());
	}

	public [Symbol.iterator](): Iterator<T> {
		return this.source[Symbol.iterator]();
	}

	/**
     * Returns a stream consisting of the elements of this stream that match the given predicate.
	 * 
	 * This is an *intermediate operation*.
     *
     * @param predicate The function that determines when an element is included.
     */
	public filter<S extends T>(predicate: (value: T) => value is S): Stream<S>
	public filter(predicate: Predicate<T>): Stream<T>
	public filter(predicate: Predicate<T>): Stream<T> {
		const source = this.source;

		return new Stream<T>((function* filter() {
			for (const element of source) if (predicate(element)) yield element;
		})());
	}

	/**
     * Returns a stream consisting of the results of applying the given function to the elements of
	 * this stream.
     *
	 * This is an *intermediate operation*.
     *
     * @param mapper The function that transforms an element into another.
     */
	public map<R>(mapper: Function<T, R>): Stream<R> {
		const source = this.source;

		return new Stream<R>((function* map() {
			for (const element of source) yield mapper(element);
		})());
	}

	/**
     * Returns a stream consisting of the results of replacing each element of this stream with the
	 * contents of a mapped stream produced by applying the provided mapping function to each element.
	 * If a mapped stream is `null` or `undefined`, an empty stream is used instead.
	 * 
	 * This is an *intermediate operation*.
     *
     * @param mapper The function that transforms an element into another.
     */
	public flatMap<U>(mapper: Function<T, Stream<U>>): Stream<U> {
		const source = this.source;

		return new Stream(function* flatMap() {
			for (const element of source) {
				const result = mapper(element) ?? Stream.empty();

				for (const inner of result.source) yield inner;
			}
		}());
	}

	/**
	 * Returns a stream consisting of the results of replacing each element of this stream with
	 * multiple elements, specifically zero or more elements. Replacement is performed by applying
	 * the provided mapping function to each element in conjunction with a `consumer` argument that
	 * accepts replacement elements. The mapping function can call the `consumer` function zero or
	 * more times to provide the replacement elements.
	 * 
	 * This is an *intermediate operation*.
	 * 
     * @param mapper A function that acceptss the stream element and another function, used for providing the replacement elements.
	 * 
	 * @example
	 * ```
	 * Stream.iterate(1, x => x + 1)
	 *        .limit(10)
	 *        .mapMulti((x, buffer) => {
	 *            for (let i = 0; i < x; i += 1) buffer(x);
	 *        });
	 * ```
	 * This example returns a `Stream` consisting of a number `x` enumerated `x` times, in order. 
	 */
	public mapMulti<R>(mapper: BiConsumer<T, Consumer<R>>): Stream<R> {
		return this.flatMap(e => {
			const elements: R[] = [];
			mapper(e, r => void elements.push(r));
			return new Stream(elements);
		});
	}

	/**
     * Returns a stream consisting of the distinct elements of this stream according to the 
	 * JavaScript Set API, via {@link Set.has `Set#has`}.
     *
     * This is a *stateful intermediate operation*.
	 */
	public distinct(): Stream<T>;
	/**
     * Returns a stream consisting of the distinct elements of this stream according to the 
	 * {@link Set.has `Set#has`} method of the created `Set` from the `setClass`.
     *
     * This is a *stateful intermediate operation*.
	 * 
	 * @param setClass The `Set` class to use in this operation.
	 */
	public distinct<S extends Set<T>>(setClass: NonAbstractClass<S>): Stream<T>;
	public distinct<S extends Set<T>>(setClass: NonAbstractClass<S> = Set<T> as unknown as NonAbstractClass<S>): Stream<T> {
		const source = this.source;

		return new Stream<T>((function* distinct() {
			const seen: Set<T> = new setClass();

			for (const element of source) {
				if (!seen.has(element)) {
					seen.add(element);

					yield element;
				}
			}
		})());
	}

	/**
     * Returns a stream consisting of the elements of this stream, sorted according to the provided
	 * `comparator`
	 * 
     * This is a *stateful intermediate operation*.
     */
	public sorted(comparator: BiFunction<T, T, number>): Stream<T> {
		const source = this.source;

		return new Stream<T>((function* sorted() {
			const values: T[] = Array.from(source).sort(comparator);

			yield* values;
		})());
	}

	/**
     * Returns a stream consisting of the elements of this stream, additionally
     * performing the provided action on each element as elements are consumed
     * from the resulting stream.
	 * 
	 * In cases where the `Stream` is able to optimize the consumption or production of elements in
	 * short-circuting terminal operations such as {@link findFirst Stream#findFirst}, the action 
	 * will not be invoked for those elements.
     *
	 * This is an *intermediate operation*.
	 * 
	 * @param action An action to perform on the elements as they are consumed from the `Stream`.
	 */
	public peek(action: Consumer<T>): Stream<T> {
		const source = this.source;

		return new Stream<T>((function* peek() {
			for (const element of source) {
				action(element);

				yield element;
			}
		})());
	}

	/**
     * Returns a stream consisting of the elements of this stream, truncated
     * to be no longer than `maxSize` in length.
	 * 
	 * If `maxSize` is a decimal value, it is truncated. If `maxSize` is a negative value, a 
	 * `RangeError` is thrown.
     *
	 * This is an *intermediate operation*.
	 * 
     * @param maxSize The number of elements the stream should be limited to.
	 */
	public limit(maxSize: number): Stream<T> {
		if (maxSize % 1 !== 0) maxSize = Math.trunc(maxSize);

		if (maxSize < 0) throw new RangeError(`The provided maxSize for Stream#limit must not be a negative value! Provided: ${maxSize}`);

		const source = this.source;

		return new Stream<T>((function* limit() {
			const iterator = source[Symbol.iterator]();
			let i = 0,
				value: IteratorResult<T, any> | undefined;

			while ((i += 1) <= maxSize && (!value || !value.done)) {
				value = iterator.next();

				yield value.value;
			}
		})());
	}

	/**
     * Returns a stream consisting of the remaining elements of this stream after discarding the 
	 * first `n` elements of the stream. If this stream contains fewer than `n` elements, an empty
	 * stream is returned.
	 * 
	 * If `n` is a decimal value, it is truncated. If `n` is a negative value, a `RangeError` is
	 * thrown.
	 * 
	 * This is an *intermediate operation*.
	 * 
     * @param n The number of leading elements to skip.
	 */
	public skip(n: number): Stream<T> {
		if (n % 1 !== 0) n = Math.trunc(n);

		if (n < 0) throw new RangeError(`The provided n for Stream#skip must not be a negative value! Provided: ${n}`);

		const source = this.source;

		return new Stream<T>((function* skip() {
			let i = 0;
			for (const element of source) {
				i += 1;
				if (i <= n) continue;

				yield element;
			}
		})());
	}

	/**
     * Performs an action for each element of this stream.
     *
     * This is a *terminal operation*.
	 * 
	 * @param action The action to perform on the elements.
	 */
	public forEach(action: Consumer<T>): void {
		for (const element of this.source) action(element);
	}

	/**
     * Performs an action for each element of this stream. An alias of {@link forEach Stream#forEach}.
     *
     * This is a *terminal operation*.
	 * 
	 * @param action The action to perform on the elements.
	 */
	public forEachOrdered(action: Consumer<T>): void {
		this.forEach(action);
	}

	/**
     * Returns an array containing the elements of this stream.
     *
     * This is a *terminal operation*.
     */
	public toArray(): T[] {
		return Array.from(this.source);
	}

	/**
	 * Performs a reduction on the elements of this stream, using the provided identity value and 
	 * the provided `accumulator` function to return the reduced value. This is equivalent to:
	 * ```
	 * let result: U;
	 * for (const element of stream) result = await accumulator(result, element);
	 * return result;
	 * ```
	 * 
     * This is a *terminal operation*.
	 * 
     * @param identity The identity value for the `accumulator` function.
	 * @param accumulator The `accumulator` function for combining two values.
	 */
	public reduce<R>(identity: R, accumulator: BiFunction<R, T, R>): R;
	public reduce<R>(identity: R, accumulator: BiFunction<R, T, R>, combiner: BiConsumer<R, R>): R;
	public reduce<R>(identity: R, accumulator: BiFunction<R, T, R>): R {
		let value = identity;

		for (const element of this.source) value = accumulator(value, element);

		return value;
	}

	/**
	 * Performs a reduction on the elements of this stream, using the provided identity value and 
	 * the provided `accumulator` function to return the reduced value. Alias for 
	 * {@link reduce Stream#reduce}.
	 * 
     * This is a *terminal operation*.
	 * 
     * @param identity The identity value for the `accumulator` function.
	 * @param accumulator The `accumulator` function for combining two values.
	 */
	public reduceOrdered<R>(identity: R, accumulator: BiFunction<R, T, R>): R {
		let value = identity;

		for (const element of this.source) value = accumulator(value, element);

		return value;
	}

	/**
     * Performs a mutable reduction operation on the elements of this stream. A mutable reduction
	 * is one in which the reduced value is a mutable result container, such as an `Array`, and
	 * elements are incorporated by mutating or updating the state of the result rather than by
	 * replacing it. This produces a result equivalent to:
	 * ```
     * const result: R = supplier();
     * for (const element of stream) accumulator(result, element);
     * return result;
	 * ```
	 * 
     * This is a *terminal operation*.
	 * 
	 * @param supplier A function that creates a mutable result container.
	 * @param accumulator A function that mutates or updates the mutable result container with the corresponding element.
	 */
	public collect<R>(supplier: Supplier<R>, accumulator: BiConsumer<R, T>): R;
	/**
     * Performs a mutable reduction operation on the elements of this stream using a `Collector`.
	 * 
     * This is a *terminal operation*.
	 * 
	 * @param collector The `Collector` to use in reducing the elements of this stream into a single result.
	 */
	public collect<A, R>(collector: Collector<T, A, R>): R;
	public collect<A, R>(supplierOrCollector: Collector<T, A, R> | Supplier<R>, accumulator?: BiConsumer<R, T>): R {
		if (typeof supplierOrCollector === "function") {
			const result: R = supplierOrCollector();

			for (const element of this.source) accumulator?.(result, element);

			return result;
		} else {
			const supplier = supplierOrCollector.supplier();
			const accumulator2 = supplierOrCollector.accumulator();
			const finisher = supplierOrCollector.finisher();

			const result: A = supplier();

			for (const element of this.source) accumulator2(element, result);

			return finisher(result);
		}
	}

	/**
     * Returns the minimum element of this stream according to the provided `comparator`.
	 * 
	 * The first element of this stream is always considered to be the minimum element unless
	 * replaced by a later element. The `comparator` function is not called here.
	 * 
     * This is a *terminal operation*.
     *
     * @param comparator A function that compares the elements of this stream.
     * @return The minimum element of this stream according to the `comparator` or `null` if no element exists.
     */
	public min(comparator: BiFunction<T, T, number>): T | null {
		let result: T | null = null,
			value: number = Number.MAX_VALUE;

		for (const element of this.source) {
			if (result === null) {
				result = element;
				continue;
			}

			const newValue = comparator(result, element);

			if (newValue < value) {
				result = element;
				value = newValue;
				continue;
			}
		}

		return result;
	}

	/**
     * Returns the maximum element of this stream according to the provided `comparator`.
	 * 
	 * The first element of this stream is always considered to be the maximum element unless
	 * replaced by a later element. The `comparator` function is not called here.
	 * 
     * This is a *terminal operation*.
     *
     * @param comparator A function that compares the elements of this stream.
     * @return The maximum element of this stream according to the `comparator` or `null` if no element exists.
     */
	public max(comparator: BiFunction<T, T, number>): T | null {
		let result: T | null = null,
			value: number = Number.MIN_VALUE;

		for (const element of this.source) {
			if (result === null) {
				result = element;
				continue;
			}

			const newValue = comparator(result, element);

			if (newValue > value) {
				result = element;
				value = newValue;
				continue;
			}
		}

		return result;
	}

	/**
	 * Returns the count of elements in this stream. 
	 * 
     * This is a *terminal operation*.
	 */
	public count(): number {
		let i = 0;

		while (!this.source[Symbol.iterator]().next().done) i += 1;

		return i;
	}

	/**
     * Returns whether any elements of this stream match the provided `predicate`.
	 * 
	 * The predicate may not be called for all elements of the stream if it is unnecessary to
	 * continue on, such as when an element that satisfies the provided `predicate` is found early
	 * in the stream. 
	 * 
	 * If the stream is empty, `false` is returned and the predicate is not evaluated.
	 * 
     * This is a *short-circuiting terminal operation*.
	 * 
     * @param predicate The predicate to apply to the elements of this stream.
	 */
	public anyMatch(predicate: Predicate<T>): boolean {
		for (const element of this.source) if (predicate(element)) return this.#makeEmptyAndReturn(true);

		return this.#makeEmptyAndReturn(false);
	}

	/**
     * Returns whether all elements of this stream match the provided `predicate`.
	 * 
	 * The predicate may not be called for all elements of the stream if it is unnecessary to
	 * continue on, such as when an element that doesn't satisfy the provided `predicate` is found
	 * early in the stream. 
	 * 
     * This is a *short-circuiting terminal operation*.
	 * 
     * @param predicate The predicate to apply to the elements of this stream.
	 */
	public allMatch(predicate: Predicate<T>): boolean {
		for (const element of this.source) if (!predicate(element)) return this.#makeEmptyAndReturn(false);

		return this.#makeEmptyAndReturn(true);
	}

	/**
     * Returns whether no elements of this stream match the provided `predicate`.
	 * 
	 * The predicate may not be called for all elements of the stream if it is unnecessary to
	 * continue on, such as when an element that satisfies the provided `predicate` is found early
	 * in the stream. 
	 * 
     * This is a *short-circuiting terminal operation*.
	 * 
     * @param predicate The predicate to apply to the elements of this stream.
	 */
	public noneMatch(predicate: Predicate<T>): boolean {
		for (const element of this.source) if (predicate(element)) return this.#makeEmptyAndReturn(false);

		return this.#makeEmptyAndReturn(true);
	}

	/**
	 * Returns the first element of this stream, or `null` if the stream is empty.
	 * 
     * This is a *short-circuiting terminal operation*.
	 */
	public findFirst(): T | null {
		return this.#makeEmptyAndReturn(this.source[Symbol.iterator]().next().value ?? null);
	}

	#makeEmpty(): void {
		// @ts-expect-error Force set.
		this["source"] = Stream.empty().source;
	}

	#makeEmptyAndReturn<R>(value: R): R;
	#makeEmptyAndReturn<R>(supplier: Supplier<R>): R;
	#makeEmptyAndReturn<R>(valueOrSupplier: R | Supplier<R>): R {
		const value = typeof valueOrSupplier === "function"
			? (valueOrSupplier as Supplier<R>)()
			: valueOrSupplier;

		this.#makeEmpty();

		return value;
	}
}

export default Stream;